emplate description
dodona-edu/universal-judge pull request #159
Opened 2021-02-24 08:11 UTC by bsels

2021-02-26 13:01 UTC, niknetniko requested changes
Looks good in general, but I'm thinking the `config.py` file is getting a bit large.

It seems to me the probability that we would want to override the description generation code in a language config is low. Additionally, most of the code seems to be relatively self-contained. As such, I would split the description generation code in another class. If we want to keep the possibility to override them, I would organise it something like this:

In `config.py`:
```python
class Language:
....
    def get_description_generator(params):
         return new DescriptionGenerator(params);
....
```

And then move all the relevant code (e.g. `types`, and the new functions) to a new class `DescriptionGenerator`. If you want to override it then, you can implement a sublcass.

----

(perhaps something for the next meeting)

I'm not 100% sure if we want to support generating the code examples with pygmentize in HTML. I wonder if supporting markdown would be enough for the kind of exercises we envision for TESTed. It just doesn't feel like the responsibility of the judge to me, but I do get why we need it if we want to generate HTML.

2021-02-26 14:03 UTC, bsels commented on tested/languages/config.py
> +        if bundle is None:
It was because if the usage with `functools.partials`, but I have changed and written a wrapper function around it.

2021-02-26 14:06 UTC, bsels commented
> I'm not 100% sure if we want to support generating the code examples with pygmentize in HTML. I wonder if supporting markdown would be enough for the kind of exercises we envision for TESTed. It just doesn't feel like the responsibility of the judge to me, but I do get why we need it if we want to generate HTML.

An additional debate if we want to link the filenames inline the statements (instead of listing them above, or probably both) then we also needed pygmentize to generate the html.

2021-02-26 14:19 UTC, niknetniko approved these changes

2021-03-03 10:38 UTC, bsels commented
Last commits reuses the description for generating the  HTML for inlining file links and avoids multiple copies of a description_generator.

2021-03-03 10:47 UTC, niknetniko approved these changes

2021-03-04 06:16 UTC, pdawyndt approved these changes

2021-03-04 06:16 UTC, pdawyndt commented on tested/languages/generator.py
> +        generated_html = generator.generate_html_code(text)[28:-14]
Add comments to explain the slice.

2021-03-04 06:16 UTC, pdawyndt commented on tested/languages/haskell/types.json
> +      "tuple": "tupel"
I would also use the spelling tuple in Dutch.

2021-03-04 06:16 UTC, pdawyndt commented on tested/languages/python/types.json
> +      "tuple": "tupel"
I would also use the spelling tuple in Dutch.

2021-03-04 06:20 UTC, pdawyndt commented
If we use the descriptief generator for the AoC exercises, it would be a good idea to inspect the diffs to see what has changed compared to the descriptions generated by the ad hoc generator. May highlight bugs in any of these generators. Would be nice if we could report on some gains made by using this more robust way of generating descriptions for a given natural language.

2021-03-04 07:52 UTC, merged