Minor fixes+additions to CLI + fixes to custom_check oracle
dodona-edu/universal-judge pull request #499
Opened 2024-02-19 19:49 UTC by JSteegmans

This pull request Fixes some minor issues with the CLI interface as well as adds the new options to have it output verbosely or even at a debug level.
Additionally the changes in the pull request came from the need to use a custom oracle which did not seem to work at all as how the docs described it. As a result I have fixed the classes defined in the documentation (and the one also not there) now properly being available in the scope of the custom oracle function so they can be used to nicely return a result and messages.

Additional to this pull request I will make a pull request in  [dodona-edu/dodona-edu.github.io](https://github.com/dodona-edu/dodona-edu.github.io) to fix the documentation on this subject as the examples and explanation for creating a custom oracle are wrong or at best very confusing, so I would also appreciate it if that also got reviewed so nobody else needs to lose as much time to this as I did.

Changes to tested.cli:
- Fixed the -f/--full options actually disabling the full output rather than enabling as its documentation explains
- Added a -v/--verbose and -d/--debug options that change the logger to add output info/debug level messages to the standard output stream, analogous to tested module itself enables these. Additionally if both are selected debug is used as it is a higher level than info
- Fied the suite path not properly being passed to the DodonaConfig, as the config expects it relative to the resources path

Changes to tested.oracles.programmed
- Fixed the Message, EvaluationResult, and ConvertedOracleContext not being available when running a custom oracle by providing them as a type alias rather than trying to simply add the module to sys.modules, which does not seem to actually make it avialable to the custom oracle function

2024-02-20 16:47 UTC, niknetniko requested changes
Thanks for your contributions! The CLI changes look good.

However, I'm not sure I understand why the changes to the oracle are necessary (the documentation might be a culprit, as it was outdated for oracles as you pointed out, apologies for that).

We use the oracles ourselves in some exercises and in our test suites, and in those cases it seems to work.
For example from our test suite:

```python
from evaluation_utils import EvaluationResult


def evaluate_something(context):
    return EvaluationResult(context.expected.strip() == context.actual.strip())
```

If this doesn't work for you, I'm interested why it doesn't work.
If you have a link to an exercise somewhere (on Dodona for example) where it doesn't work, this would be very helpful.

The current changes to the oracle break the tests (and compatibility with existing exercises).
The test suite reports 40 errors `ModuleNotFoundError: No module named 'evaluation_utils'`.

The current oracle changes also break the tests, with 40 errors (the same error being `ModuleNotFoundError: No module named 'evaluation_utils'`).

Since the CI doesn't seem to run, it would also be nice to run `black tested/ tests/` and `isort tested/ tests/` to format the code.

2024-02-20 17:05 UTC, JSteegmans commented
Ok looking at this I suspect you are right that the outdated/incomplete documentation is likely the culprit. I was under the impression that the adding of the `evaluation_utils` module to `sys. modules` was supposed to cause it to be loaded in the current context and not that I had to also load the classes manually from a module called `evaluation_utils` (mind you this is confusing considering there is also an `evaluation_utils.py` file that gets generated at execution time in the common folder of the workdir of the judge. This file defines a Message and EvaluationResult class but not a ConvertedOracleContext).

I quickly tested it by replacing my changes in the programmed.py file with the old version and that definitely still works as well now that I added the `import` statement to the oracle file. Feel free to revert my changes in that file, although the documentation definitely needs to be updated to reflect requiring this import.

2024-02-20 17:18 UTC, JSteegmans commented
Small update: I also quickly updated the PR request for the documention to reflect this clarification of requiring the import

2024-02-21 12:03 UTC, niknetniko approved these changes
I have modified the PR to only contain the changes to the CLI

2024-02-21 12:03 UTC, merged