Add C++
dodona-edu/universal-judge pull request #532
Opened 2024-07-17 13:03 UTC by jorg-vr

This pr adds c++ to TESTed.

It is compiled using `gcc  10.2.1`.  The current version supports all `c++ 17` features and some `c++ 20` features.

### Convention choices:
I have chosen to prefer `std` types over standard `c` types. So even though you could write valid `c++` without using any `std` types, this won't work well with our judge as we try to follow best practices.

I used the string key `cpp` instead of `c++`. Both are commonly used, but the first is less likely to cause issues of being parsed incorrectly.

Heterogeneous collections are supported using `std::variant`.

Value arguments to a function are always cast to their type. This is done because not all types are well defined by how a value is written, and if the student uses templates for arguments this can cause compiler issues, without any type info present.

### Limitations
TESTed cannot differentiate between applying functions on `objects`, `pointers` and `classes` or `namespaces`.
As all three have their own operator in `c++` (`.`, `->` and `::` respectively), I could not generate code that works in all cases. For this reason I made the following choices:
- By default we always assume objects (and thus use the `.` operator)
- If we got a PascalCase identifier, I've assumed it is a class and thus used `::`. This is the only case where `::` is generated.
- pointers are not supported (`->` is never generated)

Custom oracles written in `c++`  require either an object with methods if the filename is camelCase or a a class with static methods if the filename is PascalCase. Simple methods are not supported as TESTed always provides the filename of the oracle as namespace to the generator. 

Typing statements isn't always easy and heavily reliant on the values. For some statements I simply do not have enough information to provide a type. Eg. `foo: list = bar()` and `foo = [bar()]` will both generate a variable `foo` of type `std::vector<std::any>`.
As all type information is lost on elements of type `std::any` these are hard to use for students and almost impossible to properly convert to json values for me. As type hinting is currently limited in TESTed, it would probably be best to use language specific statements in these cases.

### Unrelated changes
I forgot to run half the tests for `cpp` as the language had to manually be specified for every test.
I have refactored this so most tests use predefined language sets from `tests/language_markers.py`.
These tests are now defined with a new helper function `all_languages_except`. This way, a new language is automatically tested on all tests, but it remains easy to exclude it from certain test if you decide this test shouldn't work for the given language.

### Observations
Adding a language to TESTed requires three main parts:
 1. a `config.py` with a class inheriting from the default language class
 2. a `generators.py` which translates the internal TESTed format into a testfile in the desired language
 3. a `templates` folder containing language specific helper functions to convert return values and errors to the `json` format expected by tested
 
Extending the `config.py` is properly done using inheretance. Filling out the required methods, which are also mostly documented.
 
The `generators.py` is badly organized. There seems to be some kind of method naming convention, as all `generators.py` files seem to be largely copied from each other.
 This results in lots of duplicate code. Because there is no clear API to implement, it is also not always clear which cases should be implemented. This part was the hardest part to write, but is mostly skimmed over in the documentation.
I think this part of the code could really benefit with some types of abstraction, such as an abstract class with methods to implement. Maybe with some different abstract subclasses for `typed` and `untyped` languages, which could also reduce code duplication. This issue could be solved with visitors as specified in  https://github.com/dodona-edu/universal-judge/issues/564

The `templates` folder was not really documented either. It took me a while to figure out what the files actually did. These files are technically not required by TESTed, but helpers for the code generated in `generators.py`. But we seem to use this for every language. So some form of specification/standardization would be helpful.
This was also hard to implement for me in `c++`, but that is just because my knowledge of `c++` wasn't good enough to properly write type generics.

To end with a more positive observation: The test catch a lot of edge cases. While it was a frustrating experience to keep fixing bugs to get each test passing, it is very clear that the test have heavily improved my initial implementation.

Closes #530

2024-07-30 18:23 UTC, Imran-imtiaz48 reviewed
Your recent updates to the Python codebase reflect a thoughtful approach to improving compatibility and feature support. The inclusion of `TypeSupport` and `AllTypes` in the imports expands the functionality of your code, making it more versatile. Updating the `initial_dependencies` method to include `"values.tpp"` demonstrates attention to necessary dependencies, ensuring comprehensive file inclusion. The addition of constructs such as `HETEROGENEOUS_COLLECTIONS`, `DEFAULT_PARAMETERS`, and `HETEROGENEOUS_ARGUMENTS` to the `supported_constructs` method significantly broadens the range of supported features, enhancing the robustness of the application. Introducing the `datatype_support` method provides a clear structure for supporting various data types, which is crucial for handling complex data structures effectively. The update to the compilation settings, specifically changing the standard from `-std=c++11` to `-std=c++17`, aligns with modern C++ practices, offering improved performance and language features. Overall, these updates enhance the code's flexibility, maintainability, and compatibility with modern standards. Great job on these comprehensive improvements!

2025-03-01 15:22 UTC, niknetniko requested changes
I have not run the code locally (NixOS :+1: ), but some comments nonetheless.

> For custom oracles written in `c++` an object `evaluator` is expected. This is different to `c#` and `java` where static class methods are used. But because in `c++` static class methods use a different operator `::` instead of `->`. And `::` is currently not supported as TESTed doesn't make this differentiation.

- [x] The problem with static stuff probably deserves its own issue so we can think about it in the future. Besides that, the reason Java and C# use static methods is that they do not have (real) top-level functions, but C++ does, so I am wondering why the language specific evaluator needs to be an object? Can it not be a function, like in C?

> Providing better support for this would require changesto the internal workings of TESTed. (which I tried to avoid in this PR) Mostly keeping track of types in more details would be required.

- [ ] If you still remember the issues you encountered or the missing data, this is probably also worth putting into an issue.

> The `generators.py` is badly organized. There seems to be some kind of method naming convention, as all `generators.py` files seem to be largely copied from each other. This results in lots of duplicate code. Because there is no clear API to implement, it is also not always clear which cases should be implemented. This part was the hardest part to write, but is mostly skimmed over in the documentation. I think this part of the code could really benefit with some types of abstraction, such as an abstract class with methods to implement. Maybe with some different abstract subclasses for `typed` and `untyped` languages, which could also reduce code duplication.

While I agree that the situation is probably not ideal, a big reason is that introducing an API/base class for this is not that simple. While al lot of languages look very similar, there are often subtle differences, and you also do not want to create generation methods with a lot of parameters, as some languages (e.g. Java) are difficult enough as-is, with the generics stuff.

There are a few things I would change about the current implementation:

- By inheriting from C, it is very easy to break C++ generation by changing stuff in C, e.g. in the `define_write_funtions` method.
- Some code is re-used, but I feel like should be overridden in the C++ implementation to generate C++ code with more best practices:
  - [ ] I would also override the methods that generate C-style includes
  - [ ] I would also override the methods that generate code with `NULL`

When taking that into account, the amount of code that is actually not overridden in the C++ implementation is not that big. For this reason, I do not think having the generator code be a class with inheritance to be a good solution to this problem. That is not to say there are no possible improvements, e.g. #564 could maybe improve the code here. The main goal with the generators has always been (for me at least) to make it as easy as possible to follow along in the code to easily debug, e.g. if some type was not correctly generated (which is why this was originally done using mako templates, but those are slow).

Similarly, in general I like to keep the language implementation independent of each other (unless explicitly with helper functions), since both the language config and the code generation are logically independent things, e.g. it might be that some language follow the same logic for generating arguments, but to me that is more a coincidence than really the same behaviour (however, there are some cases where the visitors or more helper functions could indeed make things a bit cleaner).

- [ ] Remove cpp inheritance on C

- [ ] And lastly, cpp should also be added to the https://github.com/dodona-edu/universal-judge/blob/master/tests/test_serialisation.py tests. Perhaps we could just take `ALL_LANGUAGES` there and remove the ones we do not want so new languages are automatically added as well.

2025-03-03 09:38 UTC, jorg-vr commented
> The problem with static stuff probably deserves its own issue so we can think about it in the future. Besides that, the reason Java and C# use static methods is that they do not have (real) top-level functions, but C++ does, so I am wondering why the language specific evaluator needs to be an object? Can it not be a function, like in C?

@niknetniko TESTed provides me with a function with a namespace `evaluator` (the filename).
`c` doesn't support namespaces at all, so this is just ignored in all cases.
But in the `cpp` I have no good way based on which I can decide to ignore the namespace. The only way I see is passing around `evaluator_names` from the `PreparedExecutionUnit` and doing a string compare to not write out the namespace in that case. Which does not feel like a good solution.

A better solution would be telling TESTed based on config that no namespace is needed for oracles in this language, and TESTed not generating it in its internal representation in that case.
Or having a separate types for the generated Oracle statements, so languages can treat them differently.
But I would suggest doing that in a separate issue and pr.

2025-03-03 16:15 UTC, jorg-vr commented
TODO:

- [ ] add stacktrace cleaner test
- [ ] add jinja test
- [ ] verify need for parallel test

2025-03-10 13:56 UTC, jorg-vr commented
Thanks again @niknetniko for the detailed and good feedback. Although it took me another week it greatly improved my code.

Biggest changes:
- I hadn't added c++ to almost half the test cases. Running them made me have to resolve a multitude of different edge cases. (again my compliments on the wide range of tests)
- I have made the code completely independent of `c` and focused on following modern `c++` standards. This made me rewrite so many parts that there is almost no code duplication left.
- I have improved support for types of heterogeneous collections by traversing all values and creating `std::variant` types instead of defaulting to `std::any`. `std::any` is now only used for unknown values, such as function results (see limitations).

2025-03-20 20:21 UTC, niknetniko approved these changes
Looks good to me

2025-03-24 14:11 UTC, merged